# Generated by Django 5.2.12 on 2026-03-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_magictoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_provider',
            field=models.CharField(blank=True, default='', help_text='gemini or anthropic', max_length=20),
        ),
    ]
