# Generated by Django 5.2.18 on 2026-10-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_email_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ai_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ai_provider',
        ),
    ]
