# Generated by Django 5.2.18 on 2026-10-09 07:43

from django.db import migrations, models


def mark_proven_emails(apps, schema_editor):
    """Accounts without a password were created by magic link or Google, which
    both prove control of the email. Password accounts stay unverified."""
    from django.db.models import Q
    User = apps.get_model('accounts', 'User')
    # Django stores unusable passwords with a leading "!"
    User.objects.filter(Q(password__startswith='!') | ~Q(google_id='')).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_ai_api_key_remove_user_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sessions_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_proven_emails, migrations.RunPython.noop),
    ]
