from django.conf import settings
from django.db import transaction
from rest_framework import serializers
import re
from .models import Page, Block, Asset, PageVersion, CustomDomain
from .block_sanitizers import validate_safe_image_url
from .block_validators import BLOCK_VALIDATORS, clean_block_data, clean_block_styles
from .permissions import is_page_owner
from .design_tokens import clean_design_tokens


# A page is a handful of landing sections: more than this is a mistake or abuse
# (2,200 blocks made a 7.8 MB public page)
MAX_BLOCKS_PER_PAGE = 100
# Blocks the dashboard card previews
LIST_PREVIEW_BLOCKS = 4
PREVIEW_BLOCKS_ATTR = 'preview_blocks_cache'


class AssetSerializer(serializers.ModelSerializer):
    url = serializers.SerializerMethodField()

    class Meta:
        model = Asset
        fields = ['id', 'name', 'file', 'url', 'mime_type', 'size', 'created_at']
        read_only_fields = ['id', 'name', 'url', 'mime_type', 'size', 'created_at']
        extra_kwargs = {'file': {'write_only': True}}

    def get_url(self, obj):
        # Relative to the site ("/media/assets/..."), not to the API host: the
        # URL is stored in pages, which must not depend on where the API runs.
        # The frontend forwards /media to the backend like it does /api.
        return obj.file.url if obj.file else ''


class BlockSerializer(serializers.ModelSerializer):
    # Block ids are generated by the client (UUID v4) so a block keeps the
    # same id before and after it is saved (ADR-014).
    id = serializers.UUIDField(required=False)

    class Meta:
        model = Block
        fields = ['id', 'type', 'order', 'data', 'styles', 'created_at', 'updated_at']
        read_only_fields = ['created_at', 'updated_at']

    def validate_styles(self, value):
        # Same rule as the WebSocket path (SEC2-007): any JSON used to be stored as is
        return clean_block_styles(value)

    def validate(self, attrs):
        attrs = super().validate(attrs)
        initial_data = getattr(self, 'initial_data', {}) or {}
        block_type = attrs.get('type') or initial_data.get('type')
        if block_type is None and self.instance is not None:
            block_type = self.instance.type

        try:
            if block_type not in BLOCK_VALIDATORS:
                raise serializers.ValidationError(f'Tipo de bloque desconocido: {block_type}.')
            if attrs.get('data') is not None:
                attrs['data'] = clean_block_data(block_type, attrs['data'], partial=self._is_partial_block_update())
        except serializers.ValidationError as exc:
            field = 'type' if block_type not in BLOCK_VALIDATORS else 'data'
            raise serializers.ValidationError({field: exc.detail})
        return attrs

    def _is_partial_block_update(self):
        initial_data = getattr(self, 'initial_data', {}) or {}
        block_id = initial_data.get('id')
        return bool(block_id) and isinstance(block_id, str) and not block_id.startswith('blk_')


class PreviewBlockSerializer(serializers.ModelSerializer):
    """Lightweight block serializer for dashboard preview thumbnails."""
    class Meta:
        model = Block
        fields = ['id', 'type', 'order', 'data']


class PageListSerializer(serializers.ModelSerializer):
    block_count = serializers.SerializerMethodField()
    owner_name = serializers.CharField(source='owner.username', read_only=True, default='')
    is_shared = serializers.SerializerMethodField()
    preview_blocks = serializers.SerializerMethodField()

    class Meta:
        model = Page
        fields = [
            'id', 'name', 'slug', 'status', 'design_tokens',
            'seo_title', 'seo_description', 'seo_canonical_url',
            'og_title', 'og_description', 'og_image', 'og_type', 'noindex', 'language',
            'block_count', 'owner_name', 'is_shared', 'preview_blocks',
            'published_at', 'has_unpublished_changes', 'version',
            'created_at', 'updated_at',
        ]
        # status only changes through the publish/unpublish actions
        read_only_fields = [
            'id', 'slug', 'status', 'published_at', 'has_unpublished_changes', 'version',
            'created_at', 'updated_at',
        ]

    def get_block_count(self, obj):
        # The list view annotates the total because it prefetches only the preview blocks
        total = getattr(obj, 'block_total', None)
        return total if total is not None else obj.blocks.count()

    def get_is_shared(self, obj):
        request = self.context.get('request')
        if request and request.user:
            return obj.owner_id != request.user.pk
        return False

    def get_preview_blocks(self, obj):
        # The list view prefetches only the first blocks, into `preview_blocks_cache`
        blocks = getattr(obj, PREVIEW_BLOCKS_ATTR, None)
        if blocks is None:
            blocks = obj.blocks.order_by('order')[:LIST_PREVIEW_BLOCKS]
        return PreviewBlockSerializer(blocks, many=True).data


class PageDetailSerializer(serializers.ModelSerializer):
    blocks = BlockSerializer(many=True)
    # Whether the requesting user owns the page: collaborators cannot publish,
    # duplicate, delete versions or regenerate it with AI (ADR-032)
    is_owner = serializers.SerializerMethodField()
    # Not the model's URLField validator, which refuses a site path such as an
    # uploaded "/media/assets/..." (SEC2-006): validate_og_image is the rule
    og_image = serializers.CharField(max_length=500, required=False, allow_blank=True, trim_whitespace=False)

    def get_is_owner(self, obj):
        request = self.context.get('request')
        user = getattr(request, 'user', None)
        return bool(user is not None and user.is_authenticated and is_page_owner(obj, user))

    def validate_design_tokens(self, value):
        return clean_design_tokens(value)

    def validate_og_image(self, value):
        return validate_safe_image_url(value)

    def validate_blocks(self, blocks):
        """At most MAX_BLOCKS_PER_PAGE; client-generated ids must be unique and must not belong to another page."""
        if len(blocks) > MAX_BLOCKS_PER_PAGE:
            raise serializers.ValidationError(f'Máximo {MAX_BLOCKS_PER_PAGE} bloques por página.')
        ids = [str(b['id']) for b in blocks if b.get('id')]
        if len(ids) != len(set(ids)):
            raise serializers.ValidationError('Hay bloques con el mismo id.')

        foreign = Block.objects.filter(id__in=ids)
        if self.instance is not None:
            foreign = foreign.exclude(page=self.instance)
        if foreign.exists():
            raise serializers.ValidationError('Algún id de bloque ya está en uso.')
        return blocks

    class Meta:
        model = Page
        fields = [
            'id', 'name', 'slug', 'status', 'design_tokens',
            'seo_title', 'seo_description', 'seo_canonical_url',
            'og_title', 'og_description', 'og_image', 'og_type', 'noindex', 'language',
            'blocks', 'published_at', 'has_unpublished_changes', 'version', 'is_owner',
            'created_at', 'updated_at',
        ]
        # status only changes through the publish/unpublish actions, so an
        # autosave can never publish or unpublish a page. The version is
        # checked and bumped by PageViewSet.update (pages/sync.py), never
        # taken from the payload.
        read_only_fields = [
            'id', 'slug', 'status', 'published_at', 'has_unpublished_changes', 'version', 'is_owner',
            'created_at', 'updated_at',
        ]

    def create(self, validated_data):
        blocks_data = validated_data.pop('blocks', [])
        page = Page.objects.create(**validated_data)
        for i, block_data in enumerate(blocks_data):
            block_data.setdefault('order', i)
            # Keeps the client-generated id when present (validated in validate_blocks)
            Block.objects.create(page=page, **block_data)
        return page

    def update(self, instance, validated_data):
        with transaction.atomic():
            blocks_data = validated_data.pop('blocks', None)

            # Update page fields
            for attr, value in validated_data.items():
                setattr(instance, attr, value)
            instance.save()

            # If blocks were provided, replace them all (full sync from frontend)
            if blocks_data is not None:
                # Convert to strings for reliable comparison (UUID vs str mismatch)
                existing_ids = {str(uid) for uid in instance.blocks.values_list('id', flat=True)}
                incoming_ids = set()

                for i, block_data in enumerate(blocks_data):
                    block_data.setdefault('order', i)
                    block_id = str(block_data.get('id', '')) if block_data.get('id') else ''

                    if block_id and block_id in existing_ids:
                        # Update existing block. data is replaced, not merged: a
                        # key the editor removed must really go (ADR-024). A stale
                        # payload can no longer drop keys it did not know about
                        # because it is refused with 409 before it gets here.
                        block = instance.blocks.get(id=block_id)
                        for attr, value in block_data.items():
                            if attr != 'id':
                                setattr(block, attr, value)
                        block.save()
                        incoming_ids.add(block_id)
                    else:
                        # New block: keeps the client-generated id when present
                        new_block = Block.objects.create(page=instance, **block_data)
                        incoming_ids.add(str(new_block.id))

                # Delete blocks that were removed
                blocks_to_delete = existing_ids - incoming_ids
                if blocks_to_delete:
                    instance.blocks.filter(id__in=blocks_to_delete).delete()

                # Clear prefetch cache so the response reflects current blocks
                if hasattr(instance, '_prefetched_objects_cache'):
                    instance._prefetched_objects_cache.pop('blocks', None)

            return instance


class PageVersionListSerializer(serializers.ModelSerializer):
    """Lightweight serializer for version listing — excludes snapshot."""
    created_by_name = serializers.CharField(source='created_by.username', read_only=True, default='')

    class Meta:
        model = PageVersion
        fields = [
            'id', 'version_number', 'trigger', 'label',
            'created_by', 'created_by_name', 'size_bytes', 'created_at',
        ]
        read_only_fields = fields


class PageVersionDetailSerializer(serializers.ModelSerializer):
    """Full serializer including snapshot and page_metadata."""
    created_by_name = serializers.CharField(source='created_by.username', read_only=True, default='')

    class Meta:
        model = PageVersion
        fields = [
            'id', 'version_number', 'trigger', 'label',
            'created_by', 'created_by_name', 'size_bytes',
            'snapshot', 'page_metadata', 'created_at',
        ]
        read_only_fields = fields


class SharePageSerializer(serializers.Serializer):
    email = serializers.EmailField()


class UnsharePageSerializer(serializers.Serializer):
    user_id = serializers.UUIDField()


class VersionLabelSerializer(serializers.Serializer):
    label = serializers.CharField(
        max_length=200,
        required=False,
        allow_blank=True,
    )


# --- Domain validation ---

DOMAIN_RE = re.compile(
    r'^(?!-)[a-zA-Z0-9-]{1,63}(?<!-)(\.[a-zA-Z0-9-]{1,63})*\.[a-zA-Z]{2,}$'
)


def is_reserved_domain(domain):
    """The app's own domains (settings.CUSTOM_DOMAINS_RESERVED) and their subdomains."""
    return any(domain == reserved or domain.endswith(f'.{reserved}') for reserved in settings.CUSTOM_DOMAINS_RESERVED)


class CustomDomainSerializer(serializers.ModelSerializer):
    page_name = serializers.CharField(source='page.name', read_only=True, default='')
    dns_instructions = serializers.SerializerMethodField()

    class Meta:
        model = CustomDomain
        fields = [
            'id', 'domain', 'page', 'page_name',
            'dns_status', 'dns_verified_at',
            'ssl_status', 'ssl_provisioned_at', 'ssl_expires_at',
            'last_dns_check_at', 'is_active',
            'dns_instructions',
            'created_at', 'updated_at',
        ]
        read_only_fields = [
            'id', 'dns_status', 'dns_verified_at',
            'ssl_status', 'ssl_provisioned_at', 'ssl_expires_at',
            'last_dns_check_at', 'is_active',
            'dns_instructions',
            'created_at', 'updated_at',
        ]

    def get_dns_instructions(self, obj):
        return {
            'cname': {
                'type': 'CNAME',
                'name': obj.domain.split('.')[0] if '.' in obj.domain else '@',
                'value': settings.CUSTOM_DOMAINS_CNAME_TARGET,
                'ttl': 3600,
            },
            'alternative_a_record': {
                'type': 'A',
                'name': '@',
                'value': settings.CUSTOM_DOMAINS_A_RECORD,
            },
        }

    def validate_domain(self, value):
        value = value.strip().lower()
        if not DOMAIN_RE.fullmatch(value):
            raise serializers.ValidationError('Formato de dominio inválido.')
        if is_reserved_domain(value):
            raise serializers.ValidationError('No puedes usar un dominio del sistema.')
        # Check uniqueness (handled by model unique but give better error)
        existing = CustomDomain.objects.filter(domain=value)
        if self.instance:
            existing = existing.exclude(pk=self.instance.pk)
        if existing.exists():
            raise serializers.ValidationError('Este dominio ya está registrado.')
        return value
