# Generated by Django 5.2.12 on 2026-03-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_owner_to_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='theme_id',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
    ]
