# Generated by Django 5.2.12 on 2026-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_theme_id_to_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_theme',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
