# Generated by Django 5.2.12 on 2026-03-16 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_custom_theme_to_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
