# Generated by Django 5.2.12 on 2026-03-17 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_add_collaborators_to_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(help_text='Complete array of blocks [{id, type, order, data, styles}, ...]')),
                ('page_metadata', models.JSONField(blank=True, default=dict, help_text='Page-level fields at the time of snapshot (name, slug, theme_id, etc.)')),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('auto_publish', 'Al publicar'), ('auto_restore', 'Antes de restaurar'), ('auto_ai_generation', 'Antes de generación IA')], default='manual', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_versions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.page')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['page', 'version_number'], name='pages_pagev_page_id_cad495_idx'), models.Index(fields=['page', 'created_at'], name='pages_pagev_page_id_6fdfba_idx')],
                'unique_together': {('page', 'version_number')},
            },
        ),
    ]
