# Generated by Django 5.2.12 on 2026-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='og_type',
            field=models.CharField(blank=True, default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_canonical_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
