# Generated by Django 5.2.12 on 2026-03-18 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_page_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('dns_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('dns_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pendiente'), ('provisioning', 'Provisionando'), ('active', 'Activo'), ('expired', 'Expirado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('ssl_provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_dns_check_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_domains', to='pages.page')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='pages.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='pages_custo_domain_b463c6_idx'), models.Index(fields=['dns_status'], name='pages_custo_dns_sta_269b15_idx')],
            },
        ),
    ]
