# Generated by Django 5.2.12 on 2026-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='design_tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
