# Generated by Django 5.2.12 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_page_design_tokens'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['owner', 'status'], name='page_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['workspace', 'status'], name='page_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['-updated_at'], name='page_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='page_slug_idx'),
        ),
    ]
