# Generated by Django 5.2.18 on 2026-10-09 11:14

import django.db.models.deletion
import pages.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_design_tokens_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PageInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=pages.models.new_invite_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=pages.models.default_invite_expiry)),
                ('max_uses', models.PositiveSmallIntegerField(default=5)),
                ('uses', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_invites', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pages.page')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='pages_pagei_expires_180ea4_idx')],
            },
        ),
    ]
