# Generated by Django 5.2.18 on 2026-10-10 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_page_version_and_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(default='es', max_length=12, validators=[django.core.validators.RegexValidator('^[a-z]{2,3}(-[A-Za-z0-9]{2,8}){0,2}$', 'Usa un código de idioma como es, en o pt-BR.')]),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_type',
            field=models.CharField(blank=True, choices=[('website', 'website'), ('article', 'article')], default='website', max_length=50),
        ),
    ]
