# Generated by Django 5.2.12 on 2026-03-17 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_add_collaborators_to_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('pageview', 'Page View'), ('click', 'Click'), ('scroll_depth', 'Scroll Depth'), ('time_on_page', 'Time on Page'), ('cta_conversion', 'CTA Conversion')], max_length=20)),
                ('block_id', models.UUIDField(blank=True, null=True)),
                ('block_type', models.CharField(blank=True, max_length=50, null=True)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('referrer', models.URLField(blank=True, max_length=2048, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=20, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='pages.page')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page', 'created_at', 'event_type'], name='idx_analytics_page_date_type'), models.Index(fields=['page', 'event_type'], name='idx_analytics_page_type'), models.Index(fields=['page', 'block_id'], name='idx_analytics_page_block')],
            },
        ),
    ]
