# Generated by Django 5.2.18 on 2026-10-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsevent',
            name='user_agent',
        ),
    ]
