# Generated by Django 5.2.18 on 2026-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='used_own_key',
            field=models.BooleanField(default=False),
        ),
    ]
