import {
  Layout,
  BoxSelect,
  MessageSquare,
  MousePointer2,
  PanelBottom,
  CreditCard,
  HelpCircle,
  Building2,
  GalleryHorizontalEnd,
  Mail,
  Code2,
  Navigation,
  Users,
  BarChart3,
  Clock,
} from 'lucide-react';

import type { BlockDefinition } from '@/types/blocks';

import HeroBlock from '@/components/blocks/HeroBlock';
import FeaturesBlock from '@/components/blocks/FeaturesBlock';
import TestimonialsBlock from '@/components/blocks/TestimonialsBlock';
import CtaBlock from '@/components/blocks/CtaBlock';
import FooterBlock from '@/components/blocks/FooterBlock';
import PricingBlock from '@/components/blocks/PricingBlock';
import FaqBlock from '@/components/blocks/FaqBlock';
import LogoCloudBlock from '@/components/blocks/LogoCloudBlock';
import GalleryBlock from '@/components/blocks/GalleryBlock';
import ContactBlock from '@/components/blocks/ContactBlock';
import CustomHtmlBlock from '@/components/blocks/CustomHtmlBlock';
import NavbarBlock from '@/components/blocks/NavbarBlock';
import TeamBlock from '@/components/blocks/TeamBlock';
import StatsBlock from '@/components/blocks/StatsBlock';
import TimelineBlock from '@/components/blocks/TimelineBlock';

export const blockRegistry: Record<string, BlockDefinition> = {
  hero: {
    type: 'hero',
    label: 'Hero Section',
    icon: Layout,
    initialData: {
      title: 'Tu Nueva Sección',
      subtitle: 'Añade una descripción cautivadora aquí.',
      buttonText: 'Acción Principal',
      badgeText: 'Nuevo Editor UI',
      secondaryButtonText: 'Saber más',
      backgroundImage: '',
      alignment: 'center',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { key: 'buttonText', label: 'Texto del Botón', type: 'text' },
      { key: 'badgeText', label: 'Texto del Badge', type: 'text' },
      { key: 'secondaryButtonText', label: 'Texto Botón Secundario', type: 'text' },
      { key: 'backgroundImage', label: 'Imagen de Fondo', type: 'image' },
      {
        key: 'alignment',
        label: 'Alineación',
        type: 'select',
        options: [
          { value: 'center', label: 'Centrado' },
          { value: 'left', label: 'Izquierda' },
        ],
      },
    ],
    component: HeroBlock,
  },
  features: {
    type: 'features',
    label: 'Features Grid',
    icon: BoxSelect,
    initialData: {
      title: 'Descubre las ventajas',
      feature1Title: 'Característica 1',
      feature1Desc: 'Descripción breve de esta característica increíble.',
      feature2Title: 'Característica 2',
      feature2Desc: 'Descripción breve de esta característica increíble.',
    },
    fields: [
      { key: 'title', label: 'Título de Sección', type: 'textarea' },
      { key: 'feature1Title', label: 'Título C1', type: 'text' },
      { key: 'feature1Desc', label: 'Descripción C1', type: 'textarea' },
      { key: 'feature2Title', label: 'Título C2', type: 'text' },
      { key: 'feature2Desc', label: 'Descripción C2', type: 'textarea' },
    ],
    component: FeaturesBlock,
  },
  testimonials: {
    type: 'testimonials',
    label: 'Testimonials',
    icon: MessageSquare,
    initialData: {
      title: 'Lo que dicen de nosotros',
      quote1: 'Este producto ha cambiado por completo la forma en que trabajamos. Simplemente brillante.',
      author1: 'María García',
      role1: 'Product Manager en TechCorp',
      quote2: 'La mejor decisión que tomamos este año. El soporte es increíble y los resultados inmediatos.',
      author2: 'Carlos Ruiz',
      role2: 'CTO en Startup.io',
    },
    fields: [
      { key: 'title', label: 'Título de Sección', type: 'textarea' },
      { key: 'quote1', label: 'Testimonio 1', type: 'textarea' },
      { key: 'author1', label: 'Autor 1', type: 'text' },
      { key: 'role1', label: 'Rol 1', type: 'text' },
      { key: 'quote2', label: 'Testimonio 2', type: 'textarea' },
      { key: 'author2', label: 'Autor 2', type: 'text' },
      { key: 'role2', label: 'Rol 2', type: 'text' },
    ],
    component: TestimonialsBlock,
  },
  cta: {
    type: 'cta',
    label: 'Call to Action',
    icon: MousePointer2,
    initialData: {
      title: 'Comienza tu viaje',
      subtitle: '',
      buttonText: 'Suscribirse',
    },
    fields: [
      { key: 'title', label: 'Título Principal', type: 'textarea' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { key: 'buttonText', label: 'Texto del Botón', type: 'text' },
    ],
    component: CtaBlock,
  },
  footer: {
    type: 'footer',
    label: 'Footer Simple',
    icon: PanelBottom,
    initialData: {
      brandName: 'Acme Corp',
      description: 'Construyendo el futuro de la web, un bloque a la vez. Únete a nuestra revolución digital.',
      copyright: '© 2026 Acme Corporation. Todos los derechos reservados.',
      link1Label: 'Producto',
      link2Label: 'Precios',
      link3Label: 'Contacto',
    },
    fields: [
      { key: 'brandName', label: 'Nombre de Marca', type: 'text' },
      { key: 'description', label: 'Descripción', type: 'textarea' },
      { key: 'link1Label', label: 'Enlace 1', type: 'text' },
      { key: 'link2Label', label: 'Enlace 2', type: 'text' },
      { key: 'link3Label', label: 'Enlace 3', type: 'text' },
      { key: 'copyright', label: 'Copyright', type: 'textarea' },
    ],
    component: FooterBlock,
  },
  pricing: {
    type: 'pricing',
    label: 'Pricing',
    icon: CreditCard,
    initialData: {
      title: 'Planes y precios',
      subtitle: 'Elige el plan que mejor se adapte a tu equipo.',
      plan1Name: 'Starter',
      plan1Price: '€19',
      plan1Features: 'Hasta 5 páginas\n1 dominio custom\nSoporte por email',
      plan1ButtonText: 'Empezar gratis',
      plan2Name: 'Pro',
      plan2Price: '€49',
      plan2Features: 'Páginas ilimitadas\nDominios ilimitados\nSoporte prioritario\nAnalytics avanzado',
      plan2ButtonText: 'Elegir Pro',
      plan2Highlighted: true,
      billingPeriod: '/mes',
      popularBadgeText: 'Popular',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { key: 'billingPeriod', label: 'Periodo de facturación', type: 'text' },
      { key: 'popularBadgeText', label: 'Texto badge popular', type: 'text' },
      { key: 'plan1Name', label: 'Plan 1 — Nombre', type: 'text' },
      { key: 'plan1Price', label: 'Plan 1 — Precio', type: 'text' },
      { key: 'plan1Features', label: 'Plan 1 — Features (1 por línea)', type: 'textarea' },
      { key: 'plan1ButtonText', label: 'Plan 1 — Botón', type: 'text' },
      { key: 'plan2Name', label: 'Plan 2 — Nombre', type: 'text' },
      { key: 'plan2Price', label: 'Plan 2 — Precio', type: 'text' },
      { key: 'plan2Features', label: 'Plan 2 — Features (1 por línea)', type: 'textarea' },
      { key: 'plan2ButtonText', label: 'Plan 2 — Botón', type: 'text' },
      { key: 'plan2Highlighted', label: 'Plan 2 destacado', type: 'toggle' },
    ],
    component: PricingBlock,
  },
  faq: {
    type: 'faq',
    label: 'FAQ',
    icon: HelpCircle,
    initialData: {
      title: 'Preguntas frecuentes',
      q1: '¿Cómo empiezo a usar el producto?',
      a1: 'Regístrate gratis, elige una plantilla y empieza a personalizar tu landing page. No necesitas conocimientos técnicos.',
      q2: '¿Puedo usar mi propio dominio?',
      a2: 'Sí, puedes conectar cualquier dominio que poseas. Te guiamos paso a paso en la configuración DNS.',
      q3: '¿Ofrecen soporte técnico?',
      a3: 'Todos los planes incluyen soporte por email. Los planes Pro y superiores tienen soporte prioritario con respuesta en menos de 24 horas.',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'q1', label: 'Pregunta 1', type: 'text' },
      { key: 'a1', label: 'Respuesta 1', type: 'textarea' },
      { key: 'q2', label: 'Pregunta 2', type: 'text' },
      { key: 'a2', label: 'Respuesta 2', type: 'textarea' },
      { key: 'q3', label: 'Pregunta 3', type: 'text' },
      { key: 'a3', label: 'Respuesta 3', type: 'textarea' },
    ],
    component: FaqBlock,
  },
  logoCloud: {
    type: 'logoCloud',
    label: 'Logo Cloud',
    icon: Building2,
    initialData: {
      title: 'Empresas que confían en nosotros',
      logo1: 'Acme Corp',
      logo2: 'TechFlow',
      logo3: 'DataPrime',
      logo4: 'CloudBase',
      logo5: 'NextWave',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'text' },
      { key: 'logo1', label: 'Empresa 1', type: 'text' },
      { key: 'logo2', label: 'Empresa 2', type: 'text' },
      { key: 'logo3', label: 'Empresa 3', type: 'text' },
      { key: 'logo4', label: 'Empresa 4', type: 'text' },
      { key: 'logo5', label: 'Empresa 5', type: 'text' },
    ],
    component: LogoCloudBlock,
  },
  gallery: {
    type: 'gallery',
    label: 'Gallery',
    icon: GalleryHorizontalEnd,
    initialData: {
      title: 'Galería',
      subtitle: 'Una muestra de nuestros mejores trabajos.',
      columns: '3',
      image1: '',
      image2: '',
      image3: '',
      image4: '',
      image5: '',
      image6: '',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      {
        key: 'columns',
        label: 'Columnas',
        type: 'select',
        options: [
          { value: '2', label: '2 columnas' },
          { value: '3', label: '3 columnas' },
          { value: '4', label: '4 columnas' },
        ],
      },
      { key: 'image1', label: 'Imagen 1', type: 'image' },
      { key: 'image2', label: 'Imagen 2', type: 'image' },
      { key: 'image3', label: 'Imagen 3', type: 'image' },
      { key: 'image4', label: 'Imagen 4', type: 'image' },
      { key: 'image5', label: 'Imagen 5', type: 'image' },
      { key: 'image6', label: 'Imagen 6', type: 'image' },
    ],
    component: GalleryBlock,
  },
  contact: {
    type: 'contact',
    label: 'Contact Form',
    icon: Mail,
    initialData: {
      title: 'Contacto',
      subtitle: '¿Tienes alguna pregunta? Escríbenos y te responderemos lo antes posible.',
      buttonText: 'Enviar mensaje',
      namePlaceholder: 'Nombre',
      emailPlaceholder: 'Email',
      messagePlaceholder: 'Tu mensaje...',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { key: 'buttonText', label: 'Texto del Botón', type: 'text' },
      { key: 'namePlaceholder', label: 'Placeholder Nombre', type: 'text' },
      { key: 'emailPlaceholder', label: 'Placeholder Email', type: 'text' },
      { key: 'messagePlaceholder', label: 'Placeholder Mensaje', type: 'text' },
    ],
    component: ContactBlock,
  },
  customHtml: {
    type: 'customHtml',
    label: 'Custom HTML',
    icon: Code2,
    initialData: {
      html: '',
    },
    fields: [
      { key: 'html', label: 'Código HTML', type: 'textarea' },
    ],
    component: CustomHtmlBlock,
  },
  navbar: {
    type: 'navbar',
    label: 'Navbar',
    icon: Navigation,
    initialData: {
      brandName: 'MiMarca',
      logoImage: '',
      link1: 'Producto',
      link2: 'Precios',
      link3: 'Blog',
      ctaText: 'Empezar',
    },
    fields: [
      { key: 'brandName', label: 'Nombre de Marca', type: 'text' },
      { key: 'logoImage', label: 'Logo', type: 'image' },
      { key: 'link1', label: 'Enlace 1', type: 'text' },
      { key: 'link2', label: 'Enlace 2', type: 'text' },
      { key: 'link3', label: 'Enlace 3', type: 'text' },
      { key: 'ctaText', label: 'Texto CTA', type: 'text' },
    ],
    component: NavbarBlock,
  },
  team: {
    type: 'team',
    label: 'Team',
    icon: Users,
    initialData: {
      title: 'Nuestro equipo',
      subtitle: 'Las personas detrás del producto que estás construyendo.',
      member1Name: 'Ana López',
      member1Role: 'CEO & Co-fundadora',
      member1Image: '',
      member2Name: 'Carlos Martín',
      member2Role: 'CTO',
      member2Image: '',
      member3Name: 'Laura García',
      member3Role: 'Head of Design',
      member3Image: '',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { key: 'member1Name', label: 'Miembro 1 — Nombre', type: 'text' },
      { key: 'member1Role', label: 'Miembro 1 — Rol', type: 'text' },
      { key: 'member1Image', label: 'Miembro 1 — Foto', type: 'image' },
      { key: 'member2Name', label: 'Miembro 2 — Nombre', type: 'text' },
      { key: 'member2Role', label: 'Miembro 2 — Rol', type: 'text' },
      { key: 'member2Image', label: 'Miembro 2 — Foto', type: 'image' },
      { key: 'member3Name', label: 'Miembro 3 — Nombre', type: 'text' },
      { key: 'member3Role', label: 'Miembro 3 — Rol', type: 'text' },
      { key: 'member3Image', label: 'Miembro 3 — Foto', type: 'image' },
    ],
    component: TeamBlock,
  },
  stats: {
    type: 'stats',
    label: 'Stats',
    icon: BarChart3,
    initialData: {
      title: 'Números que hablan',
      subtitle: 'Nuestro impacto en cifras reales.',
      stat1Value: '10K+',
      stat1Label: 'Usuarios activos',
      stat2Value: '99.9%',
      stat2Label: 'Uptime',
      stat3Value: '150+',
      stat3Label: 'Países',
      stat4Value: '4.9/5',
      stat4Label: 'Valoración',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { key: 'stat1Value', label: 'Stat 1 — Valor', type: 'text' },
      { key: 'stat1Label', label: 'Stat 1 — Etiqueta', type: 'text' },
      { key: 'stat2Value', label: 'Stat 2 — Valor', type: 'text' },
      { key: 'stat2Label', label: 'Stat 2 — Etiqueta', type: 'text' },
      { key: 'stat3Value', label: 'Stat 3 — Valor', type: 'text' },
      { key: 'stat3Label', label: 'Stat 3 — Etiqueta', type: 'text' },
      { key: 'stat4Value', label: 'Stat 4 — Valor', type: 'text' },
      { key: 'stat4Label', label: 'Stat 4 — Etiqueta', type: 'text' },
    ],
    component: StatsBlock,
  },
  timeline: {
    type: 'timeline',
    label: 'Timeline',
    icon: Clock,
    initialData: {
      title: 'Nuestra historia',
      item1Date: 'Enero 2024',
      item1Title: 'Fundación',
      item1Desc: 'Nace la idea y se forma el equipo fundador con la visión de transformar la industria.',
      item2Date: 'Junio 2024',
      item2Title: 'Lanzamiento beta',
      item2Desc: 'Primeros 1.000 usuarios prueban la plataforma y nos ayudan a iterar rápidamente.',
      item3Date: 'Enero 2025',
      item3Title: 'Lanzamiento público',
      item3Desc: 'Disponible para todos. Más de 10.000 usuarios en el primer mes.',
    },
    fields: [
      { key: 'title', label: 'Título', type: 'textarea' },
      { key: 'item1Date', label: 'Evento 1 — Fecha', type: 'text' },
      { key: 'item1Title', label: 'Evento 1 — Título', type: 'text' },
      { key: 'item1Desc', label: 'Evento 1 — Descripción', type: 'textarea' },
      { key: 'item2Date', label: 'Evento 2 — Fecha', type: 'text' },
      { key: 'item2Title', label: 'Evento 2 — Título', type: 'text' },
      { key: 'item2Desc', label: 'Evento 2 — Descripción', type: 'textarea' },
      { key: 'item3Date', label: 'Evento 3 — Fecha', type: 'text' },
      { key: 'item3Title', label: 'Evento 3 — Título', type: 'text' },
      { key: 'item3Desc', label: 'Evento 3 — Descripción', type: 'textarea' },
    ],
    component: TimelineBlock,
  },
};

export function getAvailableBlocks() {
  return Object.values(blockRegistry).map((b) => ({
    type: b.type,
    label: b.label,
    icon: b.icon,
    initialData: b.initialData,
  }));
}
